#!/bin/bash
# This script by MitraLola716 (http://github.com/mitralola716)

# Mengecek apakah paket luci-app-tinyfm sudah terinstall atau belum
if [ -z "$(opkg list-installed | grep luci-app-tinyfm)" ]; then
    echo "Paket luci-app-tinyfm belum terinstall"
    echo "Menginstall Paket luci-app-tinyfm"
    echo "Mohon tunggu.."
    # Update repository dan install paket luci-app-tinyfm
    opkg update >/dev/null 2>&1
    opkg install luci-app-tinyfm >/dev/null 2>&1

    echo "Paket luci-app-tinyfm berhasil diinstall"
else
    echo "Paket luci-app-tinyfm sudah terinstall"
fi

# Memeriksa versi terinstall dari paket luci-app-ocgen
echo "Checking Version"
sleep 3

# Get latest version from Github
lates=$(curl -s https://api.github.com/repos/mitralola716/ocgen/releases/latest | grep -o '"tag_name": ".*"' | sed 's/"//g' | sed 's/tag_name: //g' | sed 's/v//g')

# Memeriksa versi terbaru paket luci-app-ocgen dari output opkg list
if [ $? -eq 0 ]; then
    clear
    ins=$(opkg list-installed luci-app-ocgen | awk '{print $3}' | cut -d' ' -f1 | awk 'NR==1' | sed 's/v//g')

    echo "Latest version from Github is $lates"
    echo "Installed version is $ins"
# Membandingkan versi terinstall dengan versi terbaru
    if [[ $lates == $ins || $(echo "$lates $ins" | tr " " "\n" | sort -V | tail -n 1) == $ins ]]; then
        clear
        echo -e "OcGen is up to date with lates version "$ins
        sleep 5
        exit
    else    
# Jika versi terbaru tersedia, update paket
        echo -e "Updating OcGen to version "$lates
        sleep 2
        clear
        echo -e "Installing..."
        wget --no-check-certificate -q "https://raw.githubusercontent.com/mitralola716/ocgen/main/ocgenup" -O /sbin/ocgenup && chmod 777 /sbin/ocgenup
        wget --no-check-certificate -q "https://raw.githubusercontent.com/mitralola716/ocgen/main/ocgen" -O /sbin/ocgen && chmod 777 /sbin/ocgen
        clear
        sleep 2
        /sbin/ocgen up
    fi 
else
    echo "Failed to get latest version from Github"
    exit 1
fi
