#!/bin/bash
# This script by MitraLola716 (http://github.com/mitralola716)
# VERSION 0.2_beta

# Memeriksa versi terinstall dari paket luci-app-ocgen
echo "Checking Version"
sleep 3

# Get latest version from Github
lates=$(curl -s https://api.github.com/repos/mitralola716/ocgen/releases/latest | grep -o '"tag_name": ".*"' | sed 's/"//g' | sed 's/tag_name: //g' | sed 's/v//g')

# Memeriksa versi terbaru paket luci-app-ocgen dari output opkg list
if [ $? -eq 0 ]; then
    clear
    ins=$(opkg list-installed luci-app-ocgen | awk '{print $3}' | cut -d' ' -f1 | awk 'NR==1' | sed 's/v//g')

    echo "Latest version from Github is $lates"
    echo "Installed version is $ins"

    if [[ $lates == $ins || $(echo "$lates $ins" | tr " " "\n" | sort -V | tail -n 1) == $ins ]]; then
        clear
        echo -e "OcGen is up to date with version "$ins
        sleep 5
        exit
    else
        echo -e "Updating OcGen to version "$lates
        sleep 2
        clear
        wget --no-check-certificate "https://raw.githubusercontent.com/mitralola716/ocgen/main/update" -O /sbin/update && chmod 777 /sbin/update
        wget --no-check-certificate "https://raw.githubusercontent.com/mitralola716/ocgen/main/ocgen" -O /sbin/ocgen && chmod 777 /sbin/ocgen
        clear
        sleep 2
        /sbin/ocgen up
    fi 
else
    echo "Failed to get latest version from Github"
    exit 1
fi
