#!/bin/bash
# This Script by MitraLola (http://github.com/mitralola716)

{
echo -e "Downloading binaries"
sleep 2
wget --no-check-certificate "https://raw.githubusercontent.com/mitralola716/ocgen/main/update" -O /sbin/update && chmod 7777 /sbin/update
clear
echo -e "Installation is completed"
sleep 3
}
