#!/bin/bash
VERSION=$(curl -s https://api.github.com/repos/mitralola716/ocgen/releases/latest | jq -r '.tag_name')


# Fungsi untuk mengupdate tools
up() {
    echo "Version: $VERSION"
    echo -e "Updating Tools"
    sleep 2
    opkg remove luci-app-ocgen
    clear
    sleep 2
    wget --no-check-certificate "https://github.com/mitralola716/ocgen/releases/download/$VERSION/luci-app-ocgen-' . $VERSION . '_all.ipk" -O /tmp/luci-app-ocgen.ipk && chmod 777 /tmp/luci-app-ocgen.ipk
    cd /tmp && opkg install luci-app-ocgen*.ipk
    
    echo -e "Update Finished"
    sleep 2
}

# Pengecekan argumen yang dimasukkan oleh pengguna
if [[ $1 == "up" ]]; then
    up # Jalankan fungsi "up" jika argumen adalah "up"
else
    echo "Please type Ocgen Up and Enter to update OcGen" # Tampilkan pesan jika argumen tidak valid
fi
