#!/bin/bash
#This script by AlkhaNET (http://github.com/alkhanet26)
# VERSION ALPHA 3.1

echo "Checking Version"
sleep 3
wget --no-check-certificate "https://raw.githubusercontent.com/mitralola716/ocgen/main/versi_yaml" -O /tmp/versi_yaml && chmod +x /tmp/versi_yaml
clear
lates=$(grep -o 'VERSION 0.2_beta' /tmp/v_ocgen | awk -F 'VERSION ' '{print $2}' | cut -d' ' -f1 | awk 'NR==1')
ins=$(grep -o 'VERSION 0.1_beta' && opkglist | awk -F 'VERSION ALPHA ' '{print $2}' | cut -d' ' -f1 | awk 'NR==1')
if [[ $lates == $ins ]]; then
    clear
    echo -e "OcGen Sudah Versi Terbaru "$in
    echo -e "Kembali Ke Menu Awal"
    sleep 5
    rm /tmp/versi_yaml
    /sbin/tools
else
    echo -e "Updating YAML Converter"
    sleep 1
    clear
    wget --no-check-certificate "https://raw.githubusercontent.com/mitralola716/ocgen/main/luci-app-ocgen.ipk" -O /tmp/luci-app-ocgen.ipk && chmod 777 /tmp/luci-app-ocgen.ipk
    clear
    sleep 2
    rm /tmp/versi_yaml
    /sbin/tools up
fi 
